name: Sysdig IaC Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  sysdig-iac-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Sysdig IaC Scan
      id: scan
      uses: sysdiglabs/scan-action@v5
      with:
        # Mode of operation - set to "iac" for Infrastructure as Code scanning
        mode: iac
        
        # Path to scan for IaC files
        iac-scan-path: .
        
        # Recursively scan all folders
        recursive: true
        
        # Sysdig Secure API token - store this as a GitHub secret
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
        
        # Sysdig Secure endpoint URL (default: https://secure.sysdig.com)
        sysdig-secure-url: https://secure.sysdig.com
        
        # Minimum severity to fail the build (low, medium, high, critical)
        minimum-severity: high
        
        # Fail the build if policy evaluation fails
        stop-on-failed-policy-eval: true
        
        # Fail the build if scanner encounters errors
        stop-on-processing-error: true
        
        # CLI scanner version (minimum 1.9.0 required for IaC mode)
        cli-scanner-version: 1.9.0
        
    - name: Upload SARIF results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: success() || failure()
      with:
        sarif_file: ${{ github.workspace }}/sarif.json
        
    - name: Upload scan results as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: sysdig-iac-scan-results
        path: sarif.json
        retention-days: 30