name: Sysdig IaC Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  sysdig-iac-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Sysdig IaC Scan
      id: scan
      uses: sysdiglabs/scan-action@v5
      with:
        mode: iac
        iac-scan-path: .
        recursive: true
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
        sysdig-secure-url: https://secure.sysdig.com
        minimum-severity: high
        stop-on-failed-policy-eval: false
        stop-on-processing-error: false
        cli-scanner-version: 1.9.0
        
    - name: Check for SARIF file
      id: check_sarif
      run: |
        if [ -f "${{ github.workspace }}/sarif.json" ]; then
          echo "sarif_exists=true" >> $GITHUB_OUTPUT
          echo "SARIF file found"
        else
          echo "sarif_exists=false" >> $GITHUB_OUTPUT
          echo "No SARIF file generated"
        fi
        
    - name: Upload SARIF results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: steps.check_sarif.outputs.sarif_exists == 'true'
      with:
        sarif_file: ${{ github.workspace }}/sarif.json
        
    - name: Display scan summary
      if: always()
      run: |
        echo "## Sysdig IaC Scan Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ "${{ steps.check_sarif.outputs.sarif_exists }}" == "true" ]; then
          echo "✅ Scan completed and SARIF report generated" >> $GITHUB_STEP_SUMMARY
          echo "View results in the Security tab" >> $GITHUB_STEP_SUMMARY
        else
          echo "⚠️ Scan completed but no SARIF report was generated" >> $GITHUB_STEP_SUMMARY
          echo "This may mean no issues were found or the scan needs configuration" >> $GITHUB_STEP_SUMMARY
        fi