name: Sysdig Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  sysdig-iac-scan:
    name: IaC Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Scan Infrastructure as Code
      id: iac-scan
      uses: sysdiglabs/scan-action@v6
      with:
        # Set mode to IaC scanning
        mode: iac
        
        # Path to scan - root directory to scan all IaC files
        iac-scan-path: .
        
        # Scan recursively through all directories
        recursive: true
        
        # Sysdig API token from GitHub secrets
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
        
        # Sysdig endpoint (default is US)
        sysdig-secure-url: https://eu1.app.sysdig.com
        
        # Use latest CLI scanner version that supports IaC
        cli-scanner-version: 1.22.3
        
        # Minimum severity to report (low, medium, high, critical)
        minimum-severity: medium
        
        # Don't fail the build on findings (set to true to fail on issues)
        stop-on-failed-policy-eval: false
        
        # Don't fail on scanner errors
        stop-on-processing-error: false
        
    - name: Upload SARIF results
      # Upload even if scan step fails
      if: success() || failure()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ github.workspace }}/sarif.json

  sysdig-image-scan:
    name: Container Image Scan
    runs-on: ubuntu-latest
    # Only run on main branch pushes
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    strategy:
      matrix:
        service:
          - vote
          - result
          - worker
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: |
        cd ${{ matrix.service }}
        docker build -t voting-app-${{ matrix.service }}:${{ github.sha }} .
        
    - name: Scan Docker image
      uses: sysdiglabs/scan-action@v6
      with:
        # Image to scan
        image-tag: voting-app-${{ matrix.service }}:${{ github.sha }}
        
        # Sysdig credentials
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
        sysdig-secure-url: https://eu1.app.sysdig.com
        
        # Severity filter
        severity-at-least: high
        
        # Fail on critical vulnerabilities
        stop-on-failed-policy-eval: true
        
    - name: Upload SARIF results
      if: success() || failure()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ github.workspace }}/sarif.json
        category: image-${{ matrix.service }}